name: Twitter Scraper

on:
  schedule:
    # Run 3 times a day: 8AM, 12PM, and 4PM EST (1PM, 5PM, 9PM UTC)
    - cron: '0 13,17,21 * * *'
  workflow_dispatch: # Allow manual trigger

jobs:
  scrape:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Debug environment
      run: |
        echo "Node version: $(node --version)"
        echo "NPM version: $(npm --version)"
        echo "Current directory: $(pwd)"
        echo "Files in directory: $(ls -la)"
        
    - name: Run Twitter Scraper
      env:
        TWITTERAPI_API_KEY: ${{ secrets.TWITTERAPI_API_KEY }}
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL }}
        SCRAPE_SCHEDULE: "0 13,17,21 * * *"
        NODE_ENV: production
      run: |
        echo "Starting scraper..."
        npm run scrape
        echo "Scraper completed"
      
    - name: Check Status
      run: |
        echo "Scraping completed at $(date)"
        echo "Check Slack for new tweets" 